### ISSUE TITLE
Trying to install; InvalidArgumentException in DatabaseManager.php line 246: Database [] not configured.

### ISSUE THREAD

**Issue by RobinRadic** [anomalylabs/streams-platform#61]
I am trying to install streams platform. But i keep getting:
`InvalidArgumentException in DatabaseManager.php line 246: Database [] not configured.`

Have the issue with both streams-platform and pyrocms.
```bash
git clone https://github.com/pyrocms/pyrocms
cd pyrocms
composer install
# exception is thrown after composer install and on visiting the URL or using artisan
```

```
exception 'InvalidArgumentException' with message 'Database [] not configured.' in /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:246
Stack trace:
#0 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(157): Illuminate\Database\DatabaseManager->getConfig(NULL)
#1 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(65): Illuminate\Database\DatabaseManager->makeConnection(NULL)
#2 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(304): Illuminate\Database\DatabaseManager->connection()
#3 /home/vagrant/vhosts/streams/vendor/anomaly/streams-platform/src/Addon/Module/Command/Handler/SetModuleStatesHandler.php(40): Illuminate\Database\DatabaseManager->__call('table', Array)
#4 /home/vagrant/vhosts/streams/vendor/anomaly/streams-platform/src/Addon/Module/Command/Handler/SetModuleStatesHandler.php(40): Illuminate\Database\DatabaseManager->table('addons_modules')
#5 [internal function]: Anomaly\Streams\Platform\Addon\Module\Command\Handler\SetModuleStatesHandler->handle(Object(Anomaly\Streams\Platform\Addon\Module\Command\SetModuleStates))
#6 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(210): call_user_func(Array, Object(Anomaly\Streams\Platform\Addon\Module\Command\SetModuleStates))
#7 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(187): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Addon\Module\Command\SetModuleStates), NULL)
#8 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesCommands.php(18): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Addon\Module\Command\SetModuleStates))
#9 /home/vagrant/vhosts/streams/vendor/anomaly/streams-platform/src/Addon/Module/ModuleServiceProvider.php(30): Anomaly\Streams\Platform\Addon\Module\ModuleServiceProvider->dispatch(Object(Anomaly\Streams\Platform\Addon\Module\Command\SetModuleStates))
#10 [internal function]: Anomaly\Streams\Platform\Addon\Module\ModuleServiceProvider->boot()
#11 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#12 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(597): Illuminate\Container\Container->call(Array)
#13 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(579): Illuminate\Foundation\Application->bootProvider(Object(Anomaly\Streams\Platform\Addon\Module\ModuleServiceProvider))
#14 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Anomaly\Streams\Platform\Addon\Module\ModuleServiceProvider), 40)
#15 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(580): array_walk(Array, Object(Closure))
#16 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#17 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(151): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#18 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(180): Illuminate\Foundation\Application->bootstrapWith(Array)
#19 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
#20 /home/vagrant/vhosts/streams/artisan(46): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}

```

**Comment by RyanThompson** [comment]
Try deleting your distribution.php configuration file and installing again. 

The distribution.php file is the “I’m installed” or not flag in a way.


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by RobinRadic** [comment]
I ran a `find -iname distribution.php` in the root site directory, it did not return any results. The file is not present in my installation.

I then also removed the whole site directory and clone/install again to verify that the file you mentioned really doesn't exist with a fresh installation. which resulted in a different error:

```bash
exception 'ReflectionException' with message 'Class Anomaly\PyrocmsDistribution\PyrocmsDistribution does not exist' in /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php:776
Stack trace:
#0 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): ReflectionClass->__construct('Anomaly\\Pyrocms...')
#1 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build('Anomaly\\Pyrocms...', Array)
#2 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(538): Illuminate\Container\Container->make('Anomaly\\Pyrocms...', Array)
#3 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(49): Illuminate\Foundation\Application->make('Anomaly\\Pyrocms...')
#4 /home/vagrant/vhosts/streams/vendor/anomaly/streams-platform/src/Addon/Distribution/Command/DetectActiveDistributionCommandHandler.php(59): app('Anomaly\\Pyrocms...')
#5 [internal function]: Anomaly\Streams\Platform\Addon\Distribution\Command\DetectActiveDistributionCommandHandler->handle(Object(Anomaly\Streams\Platform\Addon\Distribution\Command\DetectActiveDistributionCommand))
#6 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(210): call_user_func(Array, Object(Anomaly\Streams\Platform\Addon\Distribution\Command\DetectActiveDistributionCommand))
#7 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(187): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Addon\Distribution\Command\DetectActiveDistributionCommand), NULL)
#8 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesCommands.php(18): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Addon\Distribution\Command\DetectActiveDistributionCommand))
#9 /home/vagrant/vhosts/streams/vendor/anomaly/streams-platform/src/Addon/Distribution/DistributionServiceProvider.php(29): Anomaly\Streams\Platform\Addon\Distribution\DistributionServiceProvider->dispatch(Object(Anomaly\Streams\Platform\Addon\Distribution\Command\DetectActiveDistributionCommand))
#10 [internal function]: Anomaly\Streams\Platform\Addon\Distribution\DistributionServiceProvider->boot()
#11 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#12 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(597): Illuminate\Container\Container->call(Array)
#13 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(579): Illuminate\Foundation\Application->bootProvider(Object(Anomaly\Streams\Platform\Addon\Distribution\DistributionServiceProvider))
#14 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Anomaly\Streams\Platform\Addon\Distribution\DistributionServiceProvider), 37)
#15 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(580): array_walk(Array, Object(Closure))
#16 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#17 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(151): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#18 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(180): Illuminate\Foundation\Application->bootstrapWith(Array)
#19 /home/vagrant/vhosts/streams/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
#20 /home/vagrant/vhosts/streams/artisan(46): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}
```

In case the pyrocms distribution was somehow at fault, i then cloned/installed the anomalylabs/streams distribution to see if that would work, which resulted in another `exception 'InvalidArgumentException' with message 'Database [] not configured.`

**Comment by RyanThompson** [comment]
When you run composer install / update it should have BOTH the streams distribution and pyrocms one as well in core/anomaly.

The reason being is that the pyrocms-distribution simply extends the streams one since at this point it doesn't need to do much more than change default theme/text.

The distribution file and database file are in config/ try deleting distribution first if there is one and database as well fi that doesn't work.

Let me know what that yields and I will get on it asap!

Thanks!

**Comment by RyanThompson** [comment]
Ahhhh you know what.. Give me a sec..

**Comment by RyanThompson** [comment]
Fixed in the last few commits leading up to this last one: https://github.com/anomalylabs/streams-platform/commit/f283b6caa41875e7b4b34fbba1bb6bf6937ff9dd

Nice catch! Thanks
